backend:
  name: github
  repo: derekkramer/gatsby-data-graphql

media_folder: static/assets
public_folder: assets

collections:
  - name: article
    label: Article
    folder: pages
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }